# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appREST', '0004_auto_20171113_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
