# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appREST', '0005_auto_20171114_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
