# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appREST', '0006_auto_20171114_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product_price',
        ),
    ]
